site_name: 'Yncrea - SYSEXP Course'

# Repository
repo_name: yncrea-sysexp
repo_url: https://github.com/jurocknsail/yncrea-sysexp
edit_uri: ""
site_description: >-
  Ce cours fait partie du cours <b>ITII 2 - SYSEXP</b> pour <b>YNCREA Toulon</b> sur les systèmes d'exploitation et principalement les connaissances Linux.
  <br><br>
  <i>Le cours se déroule sur 4 jours et demi et vise à donner aux étudiants un aperçu de la façon de travailler du système d'exploitation et de se familiariser avec les bases de Linux.</i>


nav:
  - Home: index.md
  - Day#1:
    - OS Introduction: 00_intro.md
  - Day#2:
    - TP Linux Commands: 02_TpCommandesLinux.md
  - Day#3:
    - TP Regexp: 03_TpRegexp.md
    - "": 03_TpRegexp.md
  - Day#4:
    - OS Introduction: 00_intro.md

theme:
  language: en
  name: 'material'
  logo: assets/images/yncrea.png
  favicon: assets/images/yncrea.png
  palette:
    primary: cyan
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs
    - instant
  custom_dir: material

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
copyright: '&copy; 2020 Julien Berger'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jurocknsail
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/julien-berger-0a9671154/

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto